/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lottoprogram;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author The Matrix
 */
/*
CA 3 FINAL LOTTO
This program:
+ Load previous entered numbers and put them into a text field (PHASEONE/TWO)
+ Save numbers(PHASEONE/TWO)
+ Delete numbers(PHASEONE/TWO)
+ Saves score (PHASETWO)
+ Allows user to delete there scores if they wish(PHASETWO)

*/
public class lottoPhaseTwoGUI extends javax.swing.JFrame {

    // set variables for lottoNumbers here
    private int randomNum, score, scoreOne, scoreTwo, scoreA, scoreOneA, scoreTwoA, scoreB, scoreOneB, scoreTwoB, test, total;
    private String ranString;
    private ArrayList<Integer> lotteryRandom = new ArrayList<>();
    
    private List<List<Integer>> lottoDraw = new ArrayList<>();
    private ArrayList<Integer> lotteryGuess = new ArrayList<Integer>();
    private ArrayList<Integer> lotteryGuessOne = new ArrayList<Integer>();
    private ArrayList<Integer> lotteryGuessTwo = new ArrayList<Integer>();
    
    private ArrayList<Integer> lotteryRandomA = new ArrayList<>();
    
    private List<List<Integer>> lottoDrawA = new ArrayList<>();
    private ArrayList<Integer> lotteryGuessA = new ArrayList<Integer>();
    private ArrayList<Integer> lotteryGuessOneA = new ArrayList<Integer>();
    private ArrayList<Integer> lotteryGuessTwoA = new ArrayList<Integer>();
    
    private ArrayList<Integer> lotteryRandomB = new ArrayList<>();
    
    private List<List<Integer>> lottoDrawB = new ArrayList<>();
    private ArrayList<Integer> lotteryGuessB = new ArrayList<Integer>();
    private ArrayList<Integer> lotteryGuessOneB = new ArrayList<Integer>();
    private ArrayList<Integer> lotteryGuessTwoB = new ArrayList<Integer>();
          /*
            scoring for lotto one
            + Line One
            + Line Two
            + Line Three
            store into displayTotalOne
            scoring for lotto plus one
            + Line One
            + Line Two
            + Line Three
            store into displayTotalPOne
            scoring for lotto plus two
            + Line One
            + Line Two
            + Line Three
            store into displayTotalTwo
        We want to display to the user there overall score for
        each lotto results for 
        we store these in an array and call a file called score.dat
        
        */
    List<Integer> displayTotalOne = new ArrayList<Integer>();
    List<Integer> displayPOne = new ArrayList<Integer>();
    List<Integer> displayTotalTwo = new ArrayList<Integer>();

    /**
     * Creates new form lottoPhaseTwoGUI
     */
    public lottoPhaseTwoGUI() {
        initComponents();
        randomNum = 1;
        score = 0;
        scoreOne = 0;
        scoreTwo = 0;
        scoreA = 0;
        scoreOneA = 0;
        scoreTwoA = 0;
        scoreB = 0;
        scoreOneB = 0;
        scoreTwoB = 0;

        lottoBtn.setEnabled(false);
        lottoPlusBtn.setEnabled(false);
        lottoPlusPlusBtn.setEnabled(false);
        
        // set our save button to enabled false
        // we do this so that we can put enabled true in our if statment,
        // checking if the numbers are valid
        saveBtn.setEnabled(false);
        //save score to true
        saveScoreBtn.setEnabled(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        LineTwoTextOne = new javax.swing.JFormattedTextField();
        jScoreTF = new javax.swing.JTextField();
        LineTwoTextTwo = new javax.swing.JFormattedTextField();
        jScoreTFII = new javax.swing.JTextField();
        LineTwoTextThree = new javax.swing.JFormattedTextField();
        jScoreTFIII = new javax.swing.JTextField();
        LineTwoTextFour = new javax.swing.JFormattedTextField();
        pyBetBtn = new javax.swing.JButton();
        LineTwoTextFive = new javax.swing.JFormattedTextField();
        msgField = new javax.swing.JTextField();
        lineThreeLbl = new javax.swing.JLabel();
        restBtn = new javax.swing.JButton();
        LineThreeTextOne = new javax.swing.JFormattedTextField();
        LineThreeTextTwo = new javax.swing.JFormattedTextField();
        LineThreeTextThree = new javax.swing.JFormattedTextField();
        LineThreeTextFour = new javax.swing.JFormattedTextField();
        LineThreeTextFive = new javax.swing.JFormattedTextField();
        lineOneLbl = new javax.swing.JLabel();
        LineOneTextOne = new javax.swing.JFormattedTextField();
        LineOneTextTwo = new javax.swing.JFormattedTextField();
        LineOneTextThree = new javax.swing.JFormattedTextField();
        LineOneTextFour = new javax.swing.JFormattedTextField();
        LineOneTextFive = new javax.swing.JFormattedTextField();
        lottoBtn = new javax.swing.JButton();
        lineTwoLbl = new javax.swing.JLabel();
        lottoDrawTextField = new javax.swing.JTextField();
        lottoPlusBtn = new javax.swing.JButton();
        jScoreTFI = new javax.swing.JTextField();
        jScoreTFIV = new javax.swing.JTextField();
        jScoreTFV = new javax.swing.JTextField();
        jScoreTFVI = new javax.swing.JTextField();
        jScoreTFVII = new javax.swing.JTextField();
        jScoreTFVIII = new javax.swing.JTextField();
        lottoPlusPlusBtn = new javax.swing.JButton();
        gameFadeLbl = new javax.swing.JLabel();
        lottoTitlePhaseTwo = new javax.swing.JLabel();
        lottoBallsImageLabel = new javax.swing.JLabel();
        lottoNumbersTitleLabel = new javax.swing.JLabel();
        lottoGamesResultsLabel = new javax.swing.JLabel();
        lineBlockOneLabel = new javax.swing.JLabel();
        msgBoxTitleLabel = new javax.swing.JLabel();
        correctBlockOneLabel = new javax.swing.JLabel();
        saveFadeLbl = new javax.swing.JLabel();
        lineBlockTwoLabel = new javax.swing.JLabel();
        correctBlockLabel = new javax.swing.JLabel();
        lineBlockThree = new javax.swing.JLabel();
        correctBlockThree = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveScoreBtn = new javax.swing.JButton();
        loadPreviousScoreBtn = new javax.swing.JButton();
        scoreControlLabel = new javax.swing.JLabel();
        betTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicyProvider(true);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setDefaultCapable(false);
        backBtn.setFocusPainted(false);
        backBtn.setFocusable(false);
        backBtn.setRequestFocusEnabled(false);
        backBtn.setVerifyInputWhenFocusTarget(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        exitBtn.setBorderPainted(false);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setDefaultCapable(false);
        exitBtn.setFocusPainted(false);
        exitBtn.setFocusable(false);
        exitBtn.setRequestFocusEnabled(false);
        exitBtn.setVerifyInputWhenFocusTarget(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        LineTwoTextOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineTwoTextOne.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        LineTwoTextOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineTwoTextOneActionPerformed(evt);
            }
        });

        jScoreTF.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTF.setBorder(null);
        jScoreTF.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTF.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTF.setVerifyInputWhenFocusTarget(false);
        jScoreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFActionPerformed(evt);
            }
        });

        LineTwoTextTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineTwoTextTwo.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        jScoreTFII.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTFII.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTFII.setBorder(null);
        jScoreTFII.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTFII.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTFII.setVerifyInputWhenFocusTarget(false);
        jScoreTFII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFIIActionPerformed(evt);
            }
        });

        LineTwoTextThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineTwoTextThree.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        jScoreTFIII.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTFIII.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTFIII.setBorder(null);
        jScoreTFIII.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTFIII.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTFIII.setVerifyInputWhenFocusTarget(false);
        jScoreTFIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFIIIActionPerformed(evt);
            }
        });

        LineTwoTextFour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineTwoTextFour.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        pyBetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PlaceY.png"))); // NOI18N
        pyBetBtn.setBorder(null);
        pyBetBtn.setBorderPainted(false);
        pyBetBtn.setContentAreaFilled(false);
        pyBetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyBetBtnActionPerformed(evt);
            }
        });

        LineTwoTextFive.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineTwoTextFive.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        msgField.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        msgField.setForeground(new java.awt.Color(255, 0, 0));
        msgField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        msgField.setToolTipText("");
        msgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgFieldActionPerformed(evt);
            }
        });

        lineThreeLbl.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lineThreeLbl.setText("Line three :");

        restBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reset2.png"))); // NOI18N
        restBtn.setBorder(null);
        restBtn.setBorderPainted(false);
        restBtn.setContentAreaFilled(false);
        restBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restBtnActionPerformed(evt);
            }
        });

        LineThreeTextOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineThreeTextOne.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        LineThreeTextOne.setMinimumSize(new java.awt.Dimension(6, 24));
        LineThreeTextOne.setPreferredSize(new java.awt.Dimension(6, 24));
        LineThreeTextOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineThreeTextOneActionPerformed(evt);
            }
        });

        LineThreeTextTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineThreeTextTwo.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        LineThreeTextThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineThreeTextThree.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        LineThreeTextFour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineThreeTextFour.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        LineThreeTextFive.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineThreeTextFive.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        lineOneLbl.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lineOneLbl.setText("Line One : ");

        LineOneTextOne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        LineOneTextOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineOneTextOne.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        LineOneTextOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineOneTextOneActionPerformed(evt);
            }
        });

        LineOneTextTwo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        LineOneTextTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineOneTextTwo.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        LineOneTextTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineOneTextTwoActionPerformed(evt);
            }
        });

        LineOneTextThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineOneTextThree.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        LineOneTextFour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineOneTextFour.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        LineOneTextFive.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineOneTextFive.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N

        lottoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lottoBpp.png"))); // NOI18N
        lottoBtn.setBorder(null);
        lottoBtn.setBorderPainted(false);
        lottoBtn.setContentAreaFilled(false);
        lottoBtn.setMaximumSize(new java.awt.Dimension(99, 33));
        lottoBtn.setMinimumSize(new java.awt.Dimension(99, 33));
        lottoBtn.setPreferredSize(new java.awt.Dimension(19, 10));
        lottoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lottoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lottoBtnMouseExited(evt);
            }
        });
        lottoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoBtnActionPerformed(evt);
            }
        });

        lineTwoLbl.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lineTwoLbl.setText("Line Two : ");

        lottoDrawTextField.setFont(new java.awt.Font("Britannic Bold", 1, 46)); // NOI18N
        lottoDrawTextField.setForeground(new java.awt.Color(153, 0, 0));
        lottoDrawTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lottoDrawTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoDrawTextFieldActionPerformed(evt);
            }
        });

        lottoPlusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lottoBp.png"))); // NOI18N
        lottoPlusBtn.setBorder(null);
        lottoPlusBtn.setBorderPainted(false);
        lottoPlusBtn.setContentAreaFilled(false);
        lottoPlusBtn.setFocusPainted(false);
        lottoPlusBtn.setMaximumSize(new java.awt.Dimension(99, 33));
        lottoPlusBtn.setMinimumSize(new java.awt.Dimension(99, 33));
        lottoPlusBtn.setPreferredSize(new java.awt.Dimension(19, 10));
        lottoPlusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lottoPlusBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lottoPlusBtnMouseExited(evt);
            }
        });
        lottoPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoPlusBtnActionPerformed(evt);
            }
        });

        jScoreTFI.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTFI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTFI.setBorder(null);
        jScoreTFI.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTFI.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTFI.setVerifyInputWhenFocusTarget(false);
        jScoreTFI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFIActionPerformed(evt);
            }
        });

        jScoreTFIV.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTFIV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTFIV.setBorder(null);
        jScoreTFIV.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTFIV.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTFIV.setVerifyInputWhenFocusTarget(false);
        jScoreTFIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFIVActionPerformed(evt);
            }
        });

        jScoreTFV.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTFV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTFV.setBorder(null);
        jScoreTFV.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTFV.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTFV.setVerifyInputWhenFocusTarget(false);
        jScoreTFV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFVActionPerformed(evt);
            }
        });

        jScoreTFVI.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTFVI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTFVI.setBorder(null);
        jScoreTFVI.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTFVI.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTFVI.setVerifyInputWhenFocusTarget(false);
        jScoreTFVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFVIActionPerformed(evt);
            }
        });

        jScoreTFVII.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTFVII.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTFVII.setBorder(null);
        jScoreTFVII.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTFVII.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTFVII.setVerifyInputWhenFocusTarget(false);
        jScoreTFVII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFVIIActionPerformed(evt);
            }
        });

        jScoreTFVIII.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        jScoreTFVIII.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jScoreTFVIII.setBorder(null);
        jScoreTFVIII.setMinimumSize(new java.awt.Dimension(30, 30));
        jScoreTFVIII.setPreferredSize(new java.awt.Dimension(30, 30));
        jScoreTFVIII.setVerifyInputWhenFocusTarget(false);
        jScoreTFVIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreTFVIIIActionPerformed(evt);
            }
        });

        lottoPlusPlusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lottoB.png"))); // NOI18N
        lottoPlusPlusBtn.setBorder(null);
        lottoPlusPlusBtn.setBorderPainted(false);
        lottoPlusPlusBtn.setContentAreaFilled(false);
        lottoPlusPlusBtn.setMaximumSize(new java.awt.Dimension(99, 33));
        lottoPlusPlusBtn.setMinimumSize(new java.awt.Dimension(99, 33));
        lottoPlusPlusBtn.setPreferredSize(new java.awt.Dimension(19, 10));
        lottoPlusPlusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lottoPlusPlusBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lottoPlusPlusBtnMouseExited(evt);
            }
        });
        lottoPlusPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoPlusPlusBtnActionPerformed(evt);
            }
        });

        gameFadeLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gameFadeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Colblack.png"))); // NOI18N
        gameFadeLbl.setLabelFor(this);

        lottoTitlePhaseTwo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lottoTitlePhaseTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LottoLogo.png"))); // NOI18N
        lottoTitlePhaseTwo.setLabelFor(this);

        lottoBallsImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lottoBallsImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lottoBallsNames.png"))); // NOI18N
        lottoBallsImageLabel.setLabelFor(this);

        lottoNumbersTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lottoNumbersTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Baner.png"))); // NOI18N
        lottoNumbersTitleLabel.setLabelFor(this);

        lottoGamesResultsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lottoGamesResultsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LottoIndex.png"))); // NOI18N
        lottoGamesResultsLabel.setLabelFor(this);

        lineBlockOneLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lineBlockOneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lotto1lineS.png"))); // NOI18N
        lineBlockOneLabel.setLabelFor(this);

        msgBoxTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        msgBoxTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Message.png"))); // NOI18N
        msgBoxTitleLabel.setLabelFor(this);

        correctBlockOneLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        correctBlockOneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lotto1lineSc.png"))); // NOI18N
        correctBlockOneLabel.setLabelFor(this);

        saveFadeLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        saveFadeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Colblack.png"))); // NOI18N
        saveFadeLbl.setLabelFor(this);

        lineBlockTwoLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lineBlockTwoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lotto2lineS.png"))); // NOI18N
        lineBlockTwoLabel.setLabelFor(this);

        correctBlockLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        correctBlockLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lotto2lineSc.png"))); // NOI18N
        correctBlockLabel.setLabelFor(this);

        lineBlockThree.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lineBlockThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lotto3lineS.png"))); // NOI18N
        lineBlockThree.setLabelFor(this);

        correctBlockThree.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        correctBlockThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lotto3lineSc.png"))); // NOI18N
        correctBlockThree.setLabelFor(this);

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setFocusPainted(false);
        saveBtn.setFocusable(false);
        saveBtn.setRequestFocusEnabled(false);
        saveBtn.setVerifyInputWhenFocusTarget(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        loadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/load.png"))); // NOI18N
        loadBtn.setBorder(null);
        loadBtn.setBorderPainted(false);
        loadBtn.setContentAreaFilled(false);
        loadBtn.setFocusPainted(false);
        loadBtn.setFocusable(false);
        loadBtn.setRequestFocusEnabled(false);
        loadBtn.setVerifyInputWhenFocusTarget(false);
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        deleteBtn.setBorder(null);
        deleteBtn.setBorderPainted(false);
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.setFocusPainted(false);
        deleteBtn.setFocusable(false);
        deleteBtn.setRequestFocusEnabled(false);
        deleteBtn.setVerifyInputWhenFocusTarget(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveScoreBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        saveScoreBtn.setBorder(null);
        saveScoreBtn.setBorderPainted(false);
        saveScoreBtn.setContentAreaFilled(false);
        saveScoreBtn.setFocusPainted(false);
        saveScoreBtn.setFocusable(false);
        saveScoreBtn.setRequestFocusEnabled(false);
        saveScoreBtn.setVerifyInputWhenFocusTarget(false);
        saveScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveScoreBtnActionPerformed(evt);
            }
        });

        loadPreviousScoreBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/load.png"))); // NOI18N
        loadPreviousScoreBtn.setBorder(null);
        loadPreviousScoreBtn.setBorderPainted(false);
        loadPreviousScoreBtn.setContentAreaFilled(false);
        loadPreviousScoreBtn.setFocusPainted(false);
        loadPreviousScoreBtn.setFocusable(false);
        loadPreviousScoreBtn.setRequestFocusEnabled(false);
        loadPreviousScoreBtn.setVerifyInputWhenFocusTarget(false);
        loadPreviousScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPreviousScoreBtnActionPerformed(evt);
            }
        });

        scoreControlLabel.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        scoreControlLabel.setText("Score Control Buttons");

        betTextLabel.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        betTextLabel.setText("Bet Control Buttons");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lottoBallsImageLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(213, 213, 213)
                                        .addComponent(lineOneLbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lottoTitlePhaseTwo)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(pyBetBtn)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(LineTwoTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineTwoTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineTwoTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineTwoTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineTwoTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(LineThreeTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineThreeTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineThreeTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineThreeTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineThreeTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(LineOneTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineOneTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineOneTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineOneTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(LineOneTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lottoPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lottoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lottoPlusPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(211, 211, 211)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                    .addComponent(lineTwoLbl)
                                                    .addComponent(lineThreeLbl))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(msgField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(msgBoxTitleLabel)
                                                .addGap(21, 21, 21))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(lineBlockOneLabel)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScoreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jScoreTFII, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScoreTFIII, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)))
                                        .addComponent(correctBlockOneLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(gameFadeLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lineBlockTwoLabel)
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScoreTFV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScoreTFIV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScoreTFI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(correctBlockLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(saveFadeLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lineBlockThree)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScoreTFVIII, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScoreTFVII, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScoreTFVI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(correctBlockThree))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(deleteBtn)
                                                    .addComponent(saveBtn)
                                                    .addComponent(loadBtn))
                                                .addGap(18, 18, 18)
                                                .addComponent(lottoGamesResultsLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(betTextLabel)
                                                .addGap(87, 87, 87)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lottoDrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(129, 129, 129)
                                                        .addComponent(lottoNumbersTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(restBtn))
                                            .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(saveScoreBtn)
                        .addGap(39, 39, 39)
                        .addComponent(scoreControlLabel)
                        .addGap(33, 33, 33)
                        .addComponent(loadPreviousScoreBtn)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lottoTitlePhaseTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineOneLbl)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(pyBetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LineOneTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineOneTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineOneTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineOneTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineOneTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lineTwoLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LineTwoTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineTwoTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineTwoTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineTwoTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineTwoTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lineThreeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LineThreeTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineThreeTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineThreeTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineThreeTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineThreeTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lottoBallsImageLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(msgBoxTitleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(msgField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lottoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lottoPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lottoPlusPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(betTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadBtn))
                            .addComponent(lottoGamesResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lottoNumbersTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lottoDrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(correctBlockThree, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lineBlockThree, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                            .addComponent(jScoreTFVI, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScoreTFVII, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScoreTFVIII, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(saveFadeLbl, javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(correctBlockLabel, javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lineBlockTwoLabel, javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(gameFadeLbl, javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(correctBlockOneLabel, javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lineBlockOneLabel, javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                            .addComponent(jScoreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScoreTFII, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(jScoreTFIII, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScoreTFI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScoreTFIV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScoreTFV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadPreviousScoreBtn)
                            .addComponent(saveScoreBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scoreControlLabel)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        // go back
        dispose();
        welcomePane wPane = new welcomePane();
        wPane.setVisible(true);
        wPane.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_backBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        // exit button
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void jScoreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jScoreTFActionPerformed

    private void jScoreTFIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScoreTFIIActionPerformed

    private void jScoreTFIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFIIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScoreTFIIIActionPerformed

    private void pyBetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyBetBtnActionPerformed
        // TODO add your handling code here:
        msgField.setForeground(new java.awt.Color(51, 204, 0));
        msgField.setText("Please choose your game");
        if (LineOneTextOne.getText().equals("0") || LineOneTextOne.getText().equals("") || LineOneTextTwo.getText().equals("0") || LineOneTextTwo.getText().equals("") || LineOneTextThree.getText().equals("0") || LineOneTextThree.getText().equals("") || LineOneTextFour.getText().equals("0") || LineOneTextFour.getText().equals("") || LineOneTextFive.getText().equals("0") || LineOneTextFive.getText().equals("") || LineTwoTextOne.getText().equals("0") || LineTwoTextOne.getText().equals("") || LineTwoTextTwo.getText().equals("0") || LineTwoTextTwo.getText().equals("") || LineTwoTextThree.getText().equals("0") || LineTwoTextThree.getText().equals("") || LineTwoTextFour.getText().equals("0") || LineTwoTextFour.getText().equals("") || LineTwoTextFive.getText().equals("0") || LineTwoTextFive.getText().equals("") || LineThreeTextOne.getText().equals("0") || LineThreeTextOne.getText().equals("") || LineThreeTextTwo.getText().equals("0") || LineThreeTextTwo.getText().equals("") || LineThreeTextThree.getText().equals("0") || LineThreeTextThree.getText().equals("") || LineThreeTextFour.getText().equals("0") || LineThreeTextFour.getText().equals("") || LineThreeTextFive.getText().equals("0") || LineThreeTextFive.getText().equals("")) {
            lottoBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Bet is invalid, please try again");
        } else {
            lottoBtn.setEnabled(true);
            lottoPlusBtn.setEnabled(true);
            lottoPlusPlusBtn.setEnabled(true);
            
            // set our save button to enabled true if the numbers are valid
            saveBtn.setEnabled(true);
        
            
        }

        // for line one no duplication
        if (LineOneTextOne.getText().equals(LineOneTextTwo.getText()) || LineOneTextOne.getText().equals(LineOneTextThree.getText()) || LineOneTextOne.getText().equals(LineOneTextFour.getText()) || LineOneTextOne.getText().equals(LineOneTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        if (LineOneTextTwo.getText().equals(LineOneTextThree.getText()) || LineOneTextTwo.getText().equals(LineOneTextFour.getText()) || LineOneTextTwo.getText().equals(LineOneTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
            
            
        }
        if (LineOneTextThree.getText().equals(LineOneTextFour.getText()) || LineOneTextThree.getText().equals(LineOneTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        if (LineOneTextFour.getText().equals(LineOneTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        ///////////////////////////////////// line two check ///////////////////////
        // for line two no duplication
        if (LineTwoTextOne.getText().equals(LineTwoTextTwo.getText()) || LineTwoTextOne.getText().equals(LineTwoTextThree.getText()) || LineTwoTextOne.getText().equals(LineTwoTextFour.getText()) || LineTwoTextOne.getText().equals(LineTwoTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        if (LineTwoTextTwo.getText().equals(LineTwoTextThree.getText()) || LineTwoTextTwo.getText().equals(LineTwoTextFour.getText()) || LineTwoTextTwo.equals(LineTwoTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        if (LineTwoTextThree.getText().equals(LineTwoTextFour.getText()) || LineTwoTextThree.getText().equals(LineTwoTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        if (LineTwoTextFour.getText().equals(LineTwoTextThree.getText()) || LineTwoTextFour.getText().equals(LineTwoTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }

        // line three no duplicates
        ///////// check line three ////////////
        if (LineThreeTextOne.getText().equals(LineThreeTextTwo.getText()) || LineThreeTextOne.getText().equals(LineThreeTextThree.getText()) || LineThreeTextOne.getText().equals(LineThreeTextFour.getText()) || LineThreeTextOne.getText().equals(LineThreeTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        if (LineThreeTextTwo.getText().equals(LineThreeTextThree.getText()) || LineThreeTextTwo.getText().equals(LineThreeTextFour.getText()) || LineThreeTextTwo.getText().equals(LineThreeTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        if (LineThreeTextThree.getText().equals(LineThreeTextFour.getText()) || LineThreeTextThree.getText().equals(LineThreeTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates ");
        }
        if (LineThreeTextFour.getText().equals(LineThreeTextFive.getText())) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("Sorry, no duplicates");
        }

        /////////////////////////////////////////////////// try catch
        //try parse the textfield into int, a letter cannot be int so
        // if letter is found it will throw an exception
        // our catch is catching so that we can display to user
        try {
            lotteryGuess.add(Integer.parseInt(LineOneTextOne.getText()));
            lotteryGuess.add(Integer.parseInt(LineOneTextTwo.getText()));
            lotteryGuess.add(Integer.parseInt(LineOneTextThree.getText()));
            lotteryGuess.add(Integer.parseInt(LineOneTextFour.getText()));
            lotteryGuess.add(Integer.parseInt(LineOneTextFive.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextOne.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextTwo.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextThree.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextFour.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextFive.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextOne.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextTwo.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextThree.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextFour.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextFive.getText()));
        } catch (NumberFormatException nfe) {
            lottoBtn.setEnabled(false);
            lottoPlusBtn.setEnabled(false);
            lottoPlusPlusBtn.setEnabled(false);
            msgField.setForeground(new java.awt.Color(255, 0, 0));
            msgField.setText("No letters allowed");
        }

        for (int i = 0; i < 5; i++) {

            test = lotteryGuess.get(i);
            if (test > 40) {
                lottoBtn.setEnabled(false);
                lottoPlusBtn.setEnabled(false);
                lottoPlusPlusBtn.setEnabled(false);
                msgField.setForeground(new java.awt.Color(255, 0, 0));
                msgField.setText("Bet is invalid, please try again");
            }
            test = lotteryGuessOne.get(i);
            if (test > 40) {
                lottoBtn.setEnabled(false);
                lottoPlusBtn.setEnabled(false);
                lottoPlusPlusBtn.setEnabled(false);
                msgField.setForeground(new java.awt.Color(255, 0, 0));
                msgField.setText("Bet is invalid, please try again");
            }
            test = lotteryGuessTwo.get(i);
            if (test > 40) {
                lottoBtn.setEnabled(false);
                lottoPlusBtn.setEnabled(false);
                lottoPlusPlusBtn.setEnabled(false);
                msgField.setForeground(new java.awt.Color(255, 0, 0));
                msgField.setText("Bet is invalid, please try again");
            }
        }

        pyBetBtn.setEnabled(false);
        ////////////////////////////////////////////////////

    }//GEN-LAST:event_pyBetBtnActionPerformed

    private void msgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgFieldActionPerformed

    private void restBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restBtnActionPerformed
        // TODO add your handling code here:
        // resetbutton!
        dispose();
        
        lottoPhaseTwoGUI lPhase2 = new lottoPhaseTwoGUI();
        lPhase2.setVisible(true);
        lPhase2.setLocationRelativeTo(null);
    }//GEN-LAST:event_restBtnActionPerformed

    private void LineOneTextOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineOneTextOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineOneTextOneActionPerformed

    private void LineOneTextTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineOneTextTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineOneTextTwoActionPerformed

    private void lottoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lottoBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/draw.png"));

    }//GEN-LAST:event_lottoBtnMouseEntered

    private void lottoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lottoBtnMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/drawreliase.png"));
    }//GEN-LAST:event_lottoBtnMouseExited

    private void lottoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoBtnActionPerformed
        // TODO add your handling code here:
        //random

        for (int i = 0; i < 5; i++) {
            do {
                randomNum = 1 + (int) (Math.random() * ((41 - 1)));
            } while ((lotteryRandom.contains(randomNum)));
            lotteryRandom.add(randomNum);
        }

       
        lotteryGuess.add(Integer.parseInt(LineOneTextOne.getText()));
        lotteryGuess.add(Integer.parseInt(LineOneTextTwo.getText()));
        lotteryGuess.add(Integer.parseInt(LineOneTextThree.getText()));
        lotteryGuess.add(Integer.parseInt(LineOneTextFour.getText()));
        lotteryGuess.add(Integer.parseInt(LineOneTextFive.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextOne.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextTwo.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextThree.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextFour.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextFive.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextOne.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextTwo.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextThree.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextFour.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextFive.getText()));
        lottoDraw.add(lotteryGuess);
        lottoDraw.add(lotteryGuessOne);
        lottoDraw.add(lotteryGuessTwo);
        ranString = lotteryRandom.get(0).toString() + "-" + lotteryRandom.get(1).toString() + "-" + lotteryRandom.get(2).toString() + "-" + lotteryRandom.get(3).toString() + "-" + lotteryRandom.get(4).toString();
        lottoDrawTextField.setText(ranString);

        //
        for (int i = 0; i < 5; i++) {
            int c = 0;

            if (lottoDraw.get(c).contains(lotteryRandom.get(i))) {
                score++;
               }
            c++;
            if (lottoDraw.get(c).contains(lotteryRandom.get(i))) {
                scoreOne++;
            }
            c++;
            if (lottoDraw.get(c).contains(lotteryRandom.get(i))) {
                scoreTwo++;

            }

        }
        /*
            store our total in the variable
        */
        
        jScoreTF.setText(Integer.toString(score));
        jScoreTFII.setText(Integer.toString(scoreOne));
        jScoreTFIII.setText(Integer.toString(scoreTwo));
        // be using this total var to store result
        total = score + scoreOne + scoreTwo;
        displayTotalOne.add(0,total);

        if (total > 0) {
            msgField.setForeground(new java.awt.Color(51, 204, 0));
            msgField.setText("You are in luck! See your results");
        } else {
            msgField.setForeground(new java.awt.Color(153, 0, 153));
            msgField.setText("Sorry... Try Again Later");
        }
        lottoBtn.setEnabled(false);
        // set save score to true
        saveScoreBtn.setEnabled(true);


    }//GEN-LAST:event_lottoBtnActionPerformed

    private void lottoDrawTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoDrawTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoDrawTextFieldActionPerformed

    private void LineThreeTextOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineThreeTextOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineThreeTextOneActionPerformed

    private void lottoPlusBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lottoPlusBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoPlusBtnMouseEntered

    private void lottoPlusBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lottoPlusBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoPlusBtnMouseExited

    private void lottoPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoPlusBtnActionPerformed
        for (int i = 0; i < 5; i++) {
            do {
                randomNum = 1 + (int) (Math.random() * ((41 - 1)));
            } while ((lotteryRandomA.contains(randomNum)));
            lotteryRandomA.add(randomNum);
        }

        lotteryGuessA.add(Integer.parseInt(LineOneTextOne.getText()));
        lotteryGuessA.add(Integer.parseInt(LineOneTextTwo.getText()));
        lotteryGuessA.add(Integer.parseInt(LineOneTextThree.getText()));
        lotteryGuessA.add(Integer.parseInt(LineOneTextFour.getText()));
        lotteryGuessA.add(Integer.parseInt(LineOneTextFive.getText()));
        lotteryGuessOneA.add(Integer.parseInt(LineTwoTextOne.getText()));
        lotteryGuessOneA.add(Integer.parseInt(LineTwoTextTwo.getText()));
        lotteryGuessOneA.add(Integer.parseInt(LineTwoTextThree.getText()));
        lotteryGuessOneA.add(Integer.parseInt(LineTwoTextFour.getText()));
        lotteryGuessOneA.add(Integer.parseInt(LineTwoTextFive.getText()));
        lotteryGuessTwoA.add(Integer.parseInt(LineThreeTextOne.getText()));
        lotteryGuessTwoA.add(Integer.parseInt(LineThreeTextTwo.getText()));
        lotteryGuessTwoA.add(Integer.parseInt(LineThreeTextThree.getText()));
        lotteryGuessTwoA.add(Integer.parseInt(LineThreeTextFour.getText()));
        lotteryGuessTwoA.add(Integer.parseInt(LineThreeTextFive.getText()));
        lottoDrawA.add(lotteryGuessA);
        lottoDrawA.add(1, lotteryGuessOneA);
        lottoDrawA.add(lotteryGuessTwoA);
        ranString = lotteryRandomA.get(0).toString() + "-" + lotteryRandomA.get(1).toString() + "-" + lotteryRandomA.get(2).toString() + "-" + lotteryRandomA.get(3).toString() + "-" + lotteryRandomA.get(4).toString();
        lottoDrawTextField.setText(ranString);

        //
        for (int i = 0; i < 5; i++) {
            int c = 0;

            if (lottoDrawA.get(c).contains(lotteryRandomA.get(i))) {
                scoreA++;

            }
            c++;
            if (lottoDrawA.get(c).contains(lotteryRandomA.get(i))) {
                scoreOneA++;

            }
            c++;
            if (lottoDrawA.get(c).contains(lotteryRandomA.get(i))) {
                scoreTwoA++;
            }
        }
        /*
            store out total in this integer
        */
        //displayTotalPOne = scoreA + scoreOneA + scoreTwoA;
        
        jScoreTFI.setText(Integer.toString(scoreA));
        jScoreTFIV.setText(Integer.toString(scoreOneA));
        jScoreTFV.setText(Integer.toString(scoreTwoA));
        // we be using this variable to store result
        total = scoreA + scoreOneA + scoreTwoA;
        displayPOne.add(0,total);
        if (total > 0) {
            msgField.setForeground(new java.awt.Color(51, 204, 0));
            msgField.setText("You are in luck! See your results");
        } else {
            msgField.setForeground(new java.awt.Color(153, 0, 153));
            msgField.setText("Sorry... Try Again Later");
        }

        lottoPlusBtn.setEnabled(false);
        //save score to true
        saveScoreBtn.setEnabled(true);



    }//GEN-LAST:event_lottoPlusBtnActionPerformed

    private void jScoreTFIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScoreTFIActionPerformed

    private void jScoreTFIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFIVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScoreTFIVActionPerformed

    private void jScoreTFVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScoreTFVActionPerformed

    private void jScoreTFVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFVIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScoreTFVIActionPerformed

    private void jScoreTFVIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFVIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScoreTFVIIActionPerformed

    private void jScoreTFVIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreTFVIIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScoreTFVIIIActionPerformed

    private void lottoPlusPlusBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lottoPlusPlusBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoPlusPlusBtnMouseEntered

    private void lottoPlusPlusBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lottoPlusPlusBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoPlusPlusBtnMouseExited

    private void lottoPlusPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoPlusPlusBtnActionPerformed
        for (int i = 0; i < 5; i++) {
            do {
                randomNum = 1 + (int) (Math.random() * ((41 - 1)));
            } while ((lotteryRandomB.contains(randomNum)));
            lotteryRandomB.add(i, randomNum);
        }

        lotteryGuessB.add(Integer.parseInt(LineOneTextOne.getText()));
        lotteryGuessB.add(Integer.parseInt(LineOneTextTwo.getText()));
        lotteryGuessB.add(Integer.parseInt(LineOneTextThree.getText()));
        lotteryGuessB.add(Integer.parseInt(LineOneTextFour.getText()));
        lotteryGuessB.add(Integer.parseInt(LineOneTextFive.getText()));
        lotteryGuessOneB.add(Integer.parseInt(LineTwoTextOne.getText()));
        lotteryGuessOneB.add(Integer.parseInt(LineTwoTextTwo.getText()));
        lotteryGuessOneB.add(Integer.parseInt(LineTwoTextThree.getText()));
        lotteryGuessOneB.add(Integer.parseInt(LineTwoTextFour.getText()));
        lotteryGuessOneB.add(Integer.parseInt(LineTwoTextFive.getText()));
        lotteryGuessTwoB.add(Integer.parseInt(LineThreeTextOne.getText()));
        lotteryGuessTwoB.add(Integer.parseInt(LineThreeTextTwo.getText()));
        lotteryGuessTwoB.add(Integer.parseInt(LineThreeTextThree.getText()));
        lotteryGuessTwoB.add(Integer.parseInt(LineThreeTextFour.getText()));
        lotteryGuessTwoB.add(Integer.parseInt(LineThreeTextFive.getText()));
        lottoDrawB.add(lotteryGuessB);
        lottoDrawB.add(lotteryGuessOneB);
        lottoDrawB.add(lotteryGuessTwoB);
        ranString = lotteryRandomB.get(0).toString() + "-" + lotteryRandomB.get(1).toString() + "-" + lotteryRandomB.get(2).toString() + "-" + lotteryRandomB.get(3).toString() + "-" + lotteryRandomB.get(4).toString();
        lottoDrawTextField.setText(ranString);

        //
        for (int i = 0; i < 5; i++) {
            int c = 0;

            if (lottoDrawB.get(c).contains(lotteryRandomB.get(i))) {
                scoreB++;
            }
                          
            c++;
            if (lottoDrawB.get(c).contains(lotteryRandomB.get(i))) {
                scoreOneB++;

            }
            c++;
            if (lottoDrawB.get(c).contains(lotteryRandomB.get(i))) {
                scoreTwoB++;

            }

        }
    
        /*
            store total in this integer
        */
        //displayTotalTwo = scoreB + scoreOneB + scoreTwoB;
        
        
        jScoreTFVI.setText(Integer.toString(scoreB));
        jScoreTFVII.setText(Integer.toString(scoreOneB));
        jScoreTFVIII.setText(Integer.toString(scoreTwoB));
        // store result into this variable
        total = scoreB + scoreOneB + scoreTwoB;
        displayTotalTwo.add(0,total);
        if (total > 0) {
            msgField.setForeground(new java.awt.Color(51, 204, 0));
            msgField.setText("You are in luck! See your results");
        } else {
            msgField.setForeground(new java.awt.Color(153, 0, 153));
            msgField.setText("Sorry... Try Again Later");
        }
        lottoPlusPlusBtn.setEnabled(false);
        //save score to true
        saveScoreBtn.setEnabled(true);
    }//GEN-LAST:event_lottoPlusPlusBtnActionPerformed
 
    private void LineTwoTextOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineTwoTextOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineTwoTextOneActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:
        // this is our load button
        // when the user saves their numbers with the save button
        // they should be able to load up their saved numbers into the textfields
           try{
            File f = new File("output2.dat");
            FileInputStream inStream = new FileInputStream(f);
            ObjectInputStream oStream = new ObjectInputStream(inStream);
            
            lotteryGuess = (ArrayList) oStream.readObject();
            lotteryGuessOne = (ArrayList) oStream.readObject();
            lotteryGuessTwo = (ArrayList) oStream.readObject();
            
            oStream.close();
            JOptionPane.showMessageDialog(null, "Reading");
            LineOneTextOne.setText(lotteryGuess.get(0).toString());
            LineOneTextTwo.setText(lotteryGuess.get(1).toString());
            LineOneTextThree.setText(lotteryGuess.get(2).toString());
            LineOneTextFour.setText(lotteryGuess.get(3).toString());
            LineOneTextFive.setText(lotteryGuess.get(4).toString());
        
            LineTwoTextOne.setText(lotteryGuessOne.get(0).toString());
            LineTwoTextTwo.setText(lotteryGuessOne.get(1).toString());
            LineTwoTextThree.setText(lotteryGuessOne.get(2).toString());
            LineTwoTextFour.setText(lotteryGuessOne.get(3).toString());
            LineTwoTextFive.setText(lotteryGuessOne.get(4).toString());
        
            LineThreeTextOne.setText(lotteryGuessTwo.get(0).toString());
            LineThreeTextTwo.setText(lotteryGuessTwo.get(1).toString());
            LineThreeTextThree.setText(lotteryGuessTwo.get(2).toString());
            LineThreeTextFour.setText(lotteryGuessTwo.get(3).toString());
            LineThreeTextFive.setText(lotteryGuessTwo.get(4).toString());
        
    
            } catch (FileNotFoundException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        // save button
        // when user presses save, the numbers will be stored in our output2.dat file
         // create object
         try{
            File f = new File ("output2.dat");
            // make score file
            File s = new File("score.dat");
            FileOutputStream os = new FileOutputStream(f);
            
            ObjectOutputStream outputStream = new ObjectOutputStream(os);
            
            outputStream.writeObject(lotteryGuess);
            outputStream.writeObject(lotteryGuessOne);
            outputStream.writeObject(lotteryGuessTwo);
            
        
            outputStream.close();
            JOptionPane.showMessageDialog(null, " You saved your numbers! ");
            /*
            LineOneTextOne.setText("");
            LineOneTextTwo.setText("");
            LineOneTextThree.setText("");
            LineOneTextFour.setText("");
            LineOneTextFive.setText("");
            
            LineTwoTextOne.setText("");
            LineTwoTextTwo.setText("");
            LineTwoTextThree.setText("");
            LineTwoTextFour.setText("");
            LineTwoTextFive.setText("");
            
            LineThreeTextOne.setText("");
            LineThreeTextTwo.setText("");
            LineThreeTextThree.setText("");
            LineThreeTextFour.setText("");
            LineThreeTextFive.setText("");
            */
        }
        catch(IOException e){
            System.out.println(e.toString() + "Error saving numbers!");
        }
        finally{
             dispose();
             lottoPhaseTwoGUI lPhaseTwo = new lottoPhaseTwoGUI();
             lPhaseTwo.setVisible(true);
             lPhaseTwo.setLocationRelativeTo(null);
         }   
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        // let the user delete all records         
        try{
            // create a new file!
            File f = new File("output2.dat");
            // create our score file
            File s = new File("score.dat");
            if(f.exists()){
                // if the file exists already, delete it
                f.delete();
            }
            if(s.exists()){
                // if the file exists show a confirm box
                int display = JOptionPane.YES_NO_OPTION;
                int r = JOptionPane.showConfirmDialog(this, "Do you want to delete your scores?", "Deleting",display);
                if(r == 0){
                    s.delete();
                }
            }
            FileOutputStream os = new FileOutputStream(f);
            ObjectOutputStream outputStream = new ObjectOutputStream(os);
            os.close();
      
        }catch(IOException e){
            System.out.println(e.toString() + "Error!");
        }
        
        // when try catch exit do this 
        finally{
     
                dispose();
                lottoPhaseTwoGUI lPhaseTwo = new lottoPhaseTwoGUI();
                lPhaseTwo.setVisible(true);
                lPhaseTwo.setLocationRelativeTo(null);
        }    
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveScoreBtnActionPerformed
        // TODO add your handling code here:
        // save the user best score from previous
           try{
               
            File s = new File ("score.dat");
            FileOutputStream os = new FileOutputStream(s);
            
            ObjectOutputStream outputStream = new ObjectOutputStream(os);
            
            outputStream.writeObject(displayTotalOne);
            outputStream.writeObject(displayPOne);
            outputStream.writeObject(displayTotalTwo);
            
            
            
            outputStream.close();
            JOptionPane.showMessageDialog(null, " You saved your score! ");
        }
        catch(IOException e){
            System.out.println(e.toString() + "Error saving numbers!");
        }
        finally{
             dispose();
             lottoPhaseTwoGUI lPhaseTwo = new lottoPhaseTwoGUI();
             lPhaseTwo.setVisible(true);
             lPhaseTwo.setLocationRelativeTo(null);
         }   
        
        
        
    }//GEN-LAST:event_saveScoreBtnActionPerformed

    private void loadPreviousScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPreviousScoreBtnActionPerformed
        // TODO add your handling code here:
        // load the user score form their previous game
              try{
            File s = new File("score.dat");
            FileInputStream inStream = new FileInputStream(s);
            ObjectInputStream oStream = new ObjectInputStream(inStream);
            
       
            
            displayTotalOne = (ArrayList) oStream.readObject();
            displayPOne = (ArrayList) oStream.readObject();
            displayTotalTwo  =(ArrayList) oStream.readObject();

            oStream.close();
            JOptionPane.showMessageDialog(null, "Reading");
            JOptionPane.showMessageDialog(null," In Lotto, your score was : " +displayTotalOne.get(0).toString()+ " Lotto Plus draw : " +displayPOne.get(0).toString()+ " Lotto Plus two " +displayTotalTwo.get(0).toString());
            LineOneTextOne.setText(lotteryGuess.get(0).toString());
            LineOneTextTwo.setText(lotteryGuess.get(1).toString());
            LineOneTextThree.setText(lotteryGuess.get(2).toString());
            LineOneTextFour.setText(lotteryGuess.get(3).toString());
            LineOneTextFive.setText(lotteryGuess.get(4).toString());

            } catch (FileNotFoundException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_loadPreviousScoreBtnActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lottoPhaseTwoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lottoPhaseTwoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lottoPhaseTwoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lottoPhaseTwoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lottoPhaseTwoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField LineOneTextFive;
    private javax.swing.JFormattedTextField LineOneTextFour;
    private javax.swing.JFormattedTextField LineOneTextOne;
    private javax.swing.JFormattedTextField LineOneTextThree;
    private javax.swing.JFormattedTextField LineOneTextTwo;
    private javax.swing.JFormattedTextField LineThreeTextFive;
    private javax.swing.JFormattedTextField LineThreeTextFour;
    private javax.swing.JFormattedTextField LineThreeTextOne;
    private javax.swing.JFormattedTextField LineThreeTextThree;
    private javax.swing.JFormattedTextField LineThreeTextTwo;
    private javax.swing.JFormattedTextField LineTwoTextFive;
    private javax.swing.JFormattedTextField LineTwoTextFour;
    private javax.swing.JFormattedTextField LineTwoTextOne;
    private javax.swing.JFormattedTextField LineTwoTextThree;
    private javax.swing.JFormattedTextField LineTwoTextTwo;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel betTextLabel;
    private javax.swing.JLabel correctBlockLabel;
    private javax.swing.JLabel correctBlockOneLabel;
    private javax.swing.JLabel correctBlockThree;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel gameFadeLbl;
    private javax.swing.JTextField jScoreTF;
    private javax.swing.JTextField jScoreTFI;
    private javax.swing.JTextField jScoreTFII;
    private javax.swing.JTextField jScoreTFIII;
    private javax.swing.JTextField jScoreTFIV;
    private javax.swing.JTextField jScoreTFV;
    private javax.swing.JTextField jScoreTFVI;
    private javax.swing.JTextField jScoreTFVII;
    private javax.swing.JTextField jScoreTFVIII;
    private javax.swing.JLabel lineBlockOneLabel;
    private javax.swing.JLabel lineBlockThree;
    private javax.swing.JLabel lineBlockTwoLabel;
    private javax.swing.JLabel lineOneLbl;
    private javax.swing.JLabel lineThreeLbl;
    private javax.swing.JLabel lineTwoLbl;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton loadPreviousScoreBtn;
    private javax.swing.JLabel lottoBallsImageLabel;
    private javax.swing.JButton lottoBtn;
    private javax.swing.JTextField lottoDrawTextField;
    private javax.swing.JLabel lottoGamesResultsLabel;
    private javax.swing.JLabel lottoNumbersTitleLabel;
    private javax.swing.JButton lottoPlusBtn;
    private javax.swing.JButton lottoPlusPlusBtn;
    private javax.swing.JLabel lottoTitlePhaseTwo;
    private javax.swing.JLabel msgBoxTitleLabel;
    private javax.swing.JTextField msgField;
    private javax.swing.JButton pyBetBtn;
    private javax.swing.JButton restBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel saveFadeLbl;
    private javax.swing.JButton saveScoreBtn;
    private javax.swing.JLabel scoreControlLabel;
    // End of variables declaration//GEN-END:variables
}
