/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lottoprogram;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author The Matrix
 */
public class lottoPhaseOneGUI extends javax.swing.JFrame {

    // set variables for lottoNumbers here
    private int randomNum, score, scoreOne, test, total, scoreTwo;
    private String ranString;
    private ArrayList<Integer> lotteryRandom = new ArrayList<>();
    private List<List<Integer>> lottoDraw = new ArrayList<>();
    private ArrayList<Integer> lotteryGuess = new ArrayList<Integer>();
    private ArrayList<Integer> lotteryGuessOne = new ArrayList<Integer>();
    private ArrayList<Integer> lotteryGuessTwo = new ArrayList<Integer>();
    
    // saving the numbers in a new array!
 
    /**
     * Creates new form lottoPhaseOneGUI
     */
    public lottoPhaseOneGUI() {
        initComponents();
        randomNum = 1;
        score = 0;
        scoreOne = 0;
        scoreTwo = 0;
        test = 0;

        drawBtn.setEnabled(false);
        // save button to disbaled
        saveNumbersBtn.setEnabled(false);
        
        // load button diabled
        loadNumbersFromFileBtn.setEnabled(true);
        
        // make our apply number btn to enbled for now

// Import Advance Images Modeles 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lottoScrollPanelOne = new javax.swing.JScrollPane();
        lottoTextArea = new javax.swing.JTextArea();
        enterTitleLbl = new javax.swing.JLabel();
        lineTwoLbl = new javax.swing.JLabel();
        LineOneTextOne = new javax.swing.JFormattedTextField();
        LineOneTextTwo = new javax.swing.JFormattedTextField();
        LineOneTextThree = new javax.swing.JFormattedTextField();
        LineOneTextFour = new javax.swing.JFormattedTextField();
        LineOneTextFive = new javax.swing.JFormattedTextField();
        lineOneLbl = new javax.swing.JLabel();
        LineTwoTextOne = new javax.swing.JFormattedTextField();
        LineTwoTextTwo = new javax.swing.JFormattedTextField();
        LineTwoTextThree = new javax.swing.JFormattedTextField();
        LineTwoTextFour = new javax.swing.JFormattedTextField();
        LineTwoTextFive = new javax.swing.JFormattedTextField();
        lineThreeLbl = new javax.swing.JLabel();
        LineThreeTextOne = new javax.swing.JFormattedTextField();
        LineThreeTextTwo = new javax.swing.JFormattedTextField();
        LineThreeTextThree = new javax.swing.JFormattedTextField();
        LineThreeTextFour = new javax.swing.JFormattedTextField();
        LineThreeTextFive = new javax.swing.JFormattedTextField();
        genLottoLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        lineOneResultLbl = new javax.swing.JLabel();
        corrOneLbl = new javax.swing.JLabel();
        lineTwoResultLbl = new javax.swing.JLabel();
        corrTwoLbl = new javax.swing.JLabel();
        lineThreeResultLbl = new javax.swing.JLabel();
        corrThreeLbl = new javax.swing.JLabel();
        drawBtn = new javax.swing.JButton();
        drawTextField = new javax.swing.JTextField();
        lineOneTF = new javax.swing.JTextField();
        lineTwoTF = new javax.swing.JTextField();
        lineThreeTF = new javax.swing.JTextField();
        pyBetBtn = new javax.swing.JButton();
        lottoMsgField = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        saveNumbersBtn = new javax.swing.JButton();
        loadNumbersFromFileBtn = new javax.swing.JButton();
        fadeLbl = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();

        lottoTextArea.setColumns(20);
        lottoTextArea.setRows(5);
        lottoScrollPanelOne.setViewportView(lottoTextArea);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        enterTitleLbl.setText("Enter you numbers below to compare with the Lotto results");

        lineTwoLbl.setText("Line Two : ");

        LineOneTextOne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        LineOneTextOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineOneTextOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineOneTextOneActionPerformed(evt);
            }
        });

        LineOneTextTwo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        LineOneTextTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LineOneTextTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineOneTextTwoActionPerformed(evt);
            }
        });

        LineOneTextThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineOneTextFour.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineOneTextFive.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lineOneLbl.setText("Line One : ");

        LineTwoTextOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineTwoTextTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineTwoTextThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineTwoTextFour.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineTwoTextFive.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lineThreeLbl.setText("Line Three :");

        LineThreeTextOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineThreeTextTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineThreeTextThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineThreeTextFour.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LineThreeTextFive.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        genLottoLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        genLottoLbl.setText("Generate Lotto Number");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        lineOneResultLbl.setText("Line One you got :");

        corrOneLbl.setText("correct!");

        lineTwoResultLbl.setText("Line Two you got :");

        corrTwoLbl.setText("correct!");

        lineThreeResultLbl.setText("Line Three you got:");

        corrThreeLbl.setText("correct!");

        drawBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/draw.png"))); // NOI18N
        drawBtn.setBorder(null);
        drawBtn.setBorderPainted(false);
        drawBtn.setContentAreaFilled(false);
        drawBtn.setMaximumSize(new java.awt.Dimension(99, 33));
        drawBtn.setMinimumSize(new java.awt.Dimension(99, 33));
        drawBtn.setPreferredSize(new java.awt.Dimension(19, 10));
        drawBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                drawBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                drawBtnMouseExited(evt);
            }
        });
        drawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawBtnActionPerformed(evt);
            }
        });

        drawTextField.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        drawTextField.setForeground(new java.awt.Color(153, 0, 0));
        drawTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        drawTextField.setText("Lotto Numbers");
        drawTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawTextFieldActionPerformed(evt);
            }
        });

        lineOneTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lineOneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineOneTFActionPerformed(evt);
            }
        });

        lineTwoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lineTwoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineTwoTFActionPerformed(evt);
            }
        });

        lineThreeTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lineThreeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineThreeTFActionPerformed(evt);
            }
        });

        pyBetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/place.png"))); // NOI18N
        pyBetBtn.setBorder(null);
        pyBetBtn.setBorderPainted(false);
        pyBetBtn.setContentAreaFilled(false);
        pyBetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyBetBtnActionPerformed(evt);
            }
        });

        lottoMsgField.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
        lottoMsgField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lottoMsgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoMsgFieldActionPerformed(evt);
            }
        });

        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        resetBtn.setBorder(null);
        resetBtn.setBorderPainted(false);
        resetBtn.setContentAreaFilled(false);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        saveNumbersBtn.setText("Save");
        saveNumbersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNumbersBtnActionPerformed(evt);
            }
        });

        loadNumbersFromFileBtn.setText("Load");
        loadNumbersFromFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadNumbersFromFileBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(fadeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineTwoLbl)
                            .addComponent(lineOneLbl)
                            .addComponent(lineThreeLbl)
                            .addComponent(backBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LineOneTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineThreeTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LineOneTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LineOneTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LineOneTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LineOneTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LineThreeTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LineThreeTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LineThreeTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LineThreeTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LineTwoTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LineTwoTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LineTwoTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LineTwoTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LineTwoTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lottoMsgField)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(drawTextField)
                                    .addGap(12, 12, 12)
                                    .addComponent(resetBtn))
                                .addComponent(genLottoLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pyBetBtn)
                                    .addGap(32, 32, 32)
                                    .addComponent(drawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lineTwoResultLbl)
                                        .addComponent(lineThreeResultLbl)
                                        .addComponent(lineOneResultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lineThreeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(corrThreeLbl))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lineOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(corrOneLbl))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lineTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(corrTwoLbl))))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(loadNumbersFromFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveNumbersBtn))
                            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(enterTitleLbl)
                        .addGap(36, 36, 36)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lineOneLbl)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lineTwoLbl)
                                    .addComponent(LineTwoTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineTwoTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineTwoTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineTwoTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineTwoTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lineThreeLbl)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterTitleLbl)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LineThreeTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LineThreeTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LineThreeTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LineThreeTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LineThreeTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LineOneTextOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LineOneTextTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LineOneTextThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LineOneTextFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LineOneTextFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(pyBetBtn))
                            .addComponent(drawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(genLottoLbl)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetBtn))
                        .addGap(18, 18, 18)
                        .addComponent(lottoMsgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(corrOneLbl)
                            .addComponent(lineOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lineOneResultLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(corrTwoLbl)
                            .addComponent(lineTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lineTwoResultLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(corrThreeLbl)
                            .addComponent(lineThreeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lineThreeResultLbl)
                            .addComponent(backBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(saveNumbersBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadNumbersFromFileBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn)
                        .addGap(6, 6, 6)))
                .addComponent(fadeLbl)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        // back button handler
        // when user presses this dispose current frame and set welcomePane to visible
        dispose();
        welcomePane wPane = new welcomePane();
        wPane.setVisible(true);

        // when called back center the frame to center of screen
        wPane.setLocationRelativeTo(null);
    }//GEN-LAST:event_backBtnActionPerformed


    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        // exit button to close program
        dispose();
        System.exit(0);

    }//GEN-LAST:event_exitBtnActionPerformed

    private void drawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawBtnActionPerformed
        // TODO add your handling code here:
        //random

        for (int i = 0; i < 5; i++) {
            do {
                randomNum = 1 + (int) (Math.random() * ((41 - 1)));
            } while ((lotteryRandom.contains(randomNum)));
            lotteryRandom.add(randomNum);
        }

       
        lotteryGuess.add(Integer.parseInt(LineOneTextOne.getText()));
        lotteryGuess.add(Integer.parseInt(LineOneTextTwo.getText()));
        lotteryGuess.add(Integer.parseInt(LineOneTextThree.getText()));
        lotteryGuess.add(Integer.parseInt(LineOneTextFour.getText()));
        lotteryGuess.add(Integer.parseInt(LineOneTextFive.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextOne.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextTwo.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextThree.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextFour.getText()));
        lotteryGuessOne.add(Integer.parseInt(LineTwoTextFive.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextOne.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextTwo.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextThree.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextFour.getText()));
        lotteryGuessTwo.add(Integer.parseInt(LineThreeTextFive.getText()));
        lottoDraw.add(lotteryGuess);
        lottoDraw.add(lotteryGuessOne);
        lottoDraw.add(lotteryGuessTwo);
        ranString = lotteryRandom.get(0).toString() + "," + lotteryRandom.get(1).toString() + "," + lotteryRandom.get(2).toString() + "," + lotteryRandom.get(3).toString() + "," + lotteryRandom.get(4).toString();
        drawTextField.setText(ranString);

//
        for (int i = 0; i < 5; i++) {
            int c = 0;

            if (lottoDraw.get(c).contains(lotteryRandom.get(i))) {
                score++;

            }
            c++;
            if (lottoDraw.get(c).contains(lotteryRandom.get(i))) {
                scoreOne++;

            }
            c++;
            if (lottoDraw.get(c).contains(lotteryRandom.get(i))) {
                scoreTwo++;

            }

        }
        System.out.println(lottoDraw.get(0).toString());
        System.out.println(lottoDraw.get(1).toString());
        System.out.println(lottoDraw.get(2).toString());
        System.out.println(lottoDraw.get(0).get(0));
        System.out.println(Integer.toString(score));

        lineOneTF.setText(Integer.toString(score));
        lineTwoTF.setText(Integer.toString(scoreOne));
        lineThreeTF.setText(Integer.toString(scoreTwo));
        total = score + scoreOne + scoreTwo;
        if (total > 0) {
            lottoMsgField.setForeground(new java.awt.Color(51, 204, 0));
            lottoMsgField.setText("You Had LUCK!! Your Results are: ");
        } else {
            lottoMsgField.setForeground(new java.awt.Color(153, 0, 153));
            lottoMsgField.setText("Sorry... Try Again Later!");
        }


    }//GEN-LAST:event_drawBtnActionPerformed


    private void drawTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drawTextFieldActionPerformed

    private void LineOneTextOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineOneTextOneActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LineOneTextOneActionPerformed

    private void LineOneTextTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineOneTextTwoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LineOneTextTwoActionPerformed

    private void lineOneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineOneTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_lineOneTFActionPerformed

    private void lineTwoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineTwoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineTwoTFActionPerformed

    private void lineThreeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineThreeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineThreeTFActionPerformed

    private void pyBetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyBetBtnActionPerformed
        // TODO add your handling code here:
        lottoMsgField.setForeground(new java.awt.Color(51, 204, 0));
        lottoMsgField.setText("Now Press DRAW Button");
        if (LineOneTextOne.getText().equals("0") || LineOneTextOne.getText().equals("") || LineOneTextTwo.getText().equals("0") || LineOneTextTwo.getText().equals("") || LineOneTextThree.getText().equals("0") || LineOneTextThree.getText().equals("") || LineOneTextFour.getText().equals("0") || LineOneTextFour.getText().equals("") || LineOneTextFive.getText().equals("0") || LineOneTextFive.getText().equals("") || LineTwoTextOne.getText().equals("0") || LineTwoTextOne.getText().equals("") || LineTwoTextTwo.getText().equals("0") || LineTwoTextTwo.getText().equals("") || LineTwoTextThree.getText().equals("0") || LineTwoTextThree.getText().equals("") || LineTwoTextFour.getText().equals("0") || LineTwoTextFour.getText().equals("") || LineTwoTextFive.getText().equals("0") || LineTwoTextFive.getText().equals("") || LineThreeTextOne.getText().equals("0") || LineThreeTextOne.getText().equals("") || LineThreeTextTwo.getText().equals("0") || LineThreeTextTwo.getText().equals("") || LineThreeTextThree.getText().equals("0") || LineThreeTextThree.getText().equals("") || LineThreeTextFour.getText().equals("0") || LineThreeTextFour.getText().equals("") || LineThreeTextFive.getText().equals("0") || LineThreeTextFive.getText().equals("")) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Not a valid bet, please RESET");
        } else {
            // set the draw button visibility to true
            drawBtn.setEnabled(true);
            
            // set save button to true as well
            saveNumbersBtn.setEnabled(true);
            
            
            
            
        }

        // for line one no duplication
        if (LineOneTextOne.getText().equals(LineOneTextTwo.getText()) || LineOneTextOne.getText().equals(LineOneTextThree.getText()) || LineOneTextOne.getText().equals(LineOneTextFour.getText()) || LineOneTextOne.getText().equals(LineOneTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineOneTextTwo.getText().equals(LineOneTextThree.getText()) || LineOneTextTwo.getText().equals(LineOneTextFour.getText()) || LineOneTextTwo.getText().equals(LineOneTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineOneTextThree.getText().equals(LineOneTextFour.getText()) || LineOneTextThree.getText().equals(LineOneTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineOneTextFour.getText().equals(LineOneTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        ///////////////////////////////////// line two check ///////////////////////
        // for line two no duplication
        if (LineTwoTextOne.getText().equals(LineTwoTextTwo.getText()) || LineTwoTextOne.getText().equals(LineTwoTextThree.getText()) || LineTwoTextOne.getText().equals(LineTwoTextFour.getText()) || LineTwoTextOne.getText().equals(LineTwoTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineTwoTextTwo.getText().equals(LineTwoTextThree.getText()) || LineTwoTextTwo.getText().equals(LineTwoTextFour.getText()) || LineTwoTextTwo.equals(LineTwoTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineTwoTextThree.getText().equals(LineTwoTextFour.getText()) || LineTwoTextThree.getText().equals(LineTwoTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineTwoTextFour.getText().equals(LineTwoTextThree.getText()) || LineTwoTextFour.getText().equals(LineTwoTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }

        // line three no duplicates
        ///////// check line three ////////////
        if (LineThreeTextOne.getText().equals(LineThreeTextTwo.getText()) || LineThreeTextOne.getText().equals(LineThreeTextThree.getText()) || LineThreeTextOne.getText().equals(LineThreeTextFour.getText()) || LineThreeTextOne.getText().equals(LineThreeTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineThreeTextTwo.getText().equals(LineThreeTextThree.getText()) || LineThreeTextTwo.getText().equals(LineThreeTextFour.getText()) || LineThreeTextTwo.getText().equals(LineThreeTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineThreeTextThree.getText().equals(LineThreeTextFour.getText()) || LineThreeTextThree.getText().equals(LineThreeTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }
        if (LineThreeTextFour.getText().equals(LineThreeTextFive.getText())) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("Sorry, no duplicates ");
        }

        /////////////////////////////////////////////////// try catch 
        //try parse the textfield into int, a letter cannot be int so
        // if letter is found it will throw an exception
        // our catch is catching so that we can display to user
        try {
            lotteryGuess.add(Integer.parseInt(LineOneTextOne.getText()));
            lotteryGuess.add(Integer.parseInt(LineOneTextTwo.getText()));
            lotteryGuess.add(Integer.parseInt(LineOneTextThree.getText()));
            lotteryGuess.add(Integer.parseInt(LineOneTextFour.getText()));
            lotteryGuess.add(Integer.parseInt(LineOneTextFive.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextOne.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextTwo.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextThree.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextFour.getText()));
            lotteryGuessOne.add(Integer.parseInt(LineTwoTextFive.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextOne.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextTwo.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextThree.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextFour.getText()));
            lotteryGuessTwo.add(Integer.parseInt(LineThreeTextFive.getText()));
        } catch (NumberFormatException nfe) {
            drawBtn.setEnabled(false);
            lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
            lottoMsgField.setText("No letters allowed");
        }

        for (int i = 0; i < 5; i++) {

            test = lotteryGuess.get(i);
            if (test > 40) {
                drawBtn.setEnabled(false);
                lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
                lottoMsgField.setText("Not a valid bet, please RESET");
            }
            test = lotteryGuessOne.get(i);
            if (test > 40) {
                drawBtn.setEnabled(false);
                lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
                lottoMsgField.setText("Not a valid bet, please RESET");
            }
            test = lotteryGuessTwo.get(i);
            if (test > 40) {
                drawBtn.setEnabled(false);
                lottoMsgField.setForeground(new java.awt.Color(255, 0, 0));
                lottoMsgField.setText("Not a valid bet, please RESET");
            }

        }

        ////////////////////////////////////////////////////

    }//GEN-LAST:event_pyBetBtnActionPerformed

    private void lottoMsgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoMsgFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_lottoMsgFieldActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        // resetbutton
        dispose(); 
        lottoPhaseOneGUI lPhaseOne = new lottoPhaseOneGUI();
        lPhaseOne.setVisible(true);
        lPhaseOne.setLocationRelativeTo(null);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void drawBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/draw.png"));

    }//GEN-LAST:event_drawBtnMouseEntered

    private void drawBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawBtnMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/drawreliase.png"));
    }//GEN-LAST:event_drawBtnMouseExited

    private void saveNumbersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNumbersBtnActionPerformed
        // TODO add your handling code here:
        // apply the numbers to our new array
        try{
            File f = new File ("output.dat");
            FileOutputStream os = new FileOutputStream(f);
            
            ObjectOutputStream outputStream = new ObjectOutputStream(os);
            
            outputStream.writeObject(lotteryGuess);
            outputStream.writeObject(lotteryGuessOne);
            outputStream.writeObject(lotteryGuessTwo);
            
            
            
            outputStream.close();
            JOptionPane.showMessageDialog(null, " You saved your numbers! ");
            /*
            LineOneTextOne.setText("");
            LineOneTextTwo.setText("");
            LineOneTextThree.setText("");
            LineOneTextFour.setText("");
            LineOneTextFive.setText("");
            
            LineTwoTextOne.setText("");
            LineTwoTextTwo.setText("");
            LineTwoTextThree.setText("");
            LineTwoTextFour.setText("");
            LineTwoTextFive.setText("");
            
            LineThreeTextOne.setText("");
            LineThreeTextTwo.setText("");
            LineThreeTextThree.setText("");
            LineThreeTextFour.setText("");
            LineThreeTextFive.setText("");
            */
        }
        catch(IOException e){
            System.out.println(e.toString() + "Error saving numbers!");
        }
        finally{
             dispose();
             lottoPhaseOneGUI lPhaseOne = new lottoPhaseOneGUI();
             lPhaseOne.setVisible(true);
             lPhaseOne.setLocationRelativeTo(null);
         }   
    }//GEN-LAST:event_saveNumbersBtnActionPerformed
    //boolean checkerIfDelete = false;

    private void loadNumbersFromFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadNumbersFromFileBtnActionPerformed
        // TODO add your handling code here:
        // load our saved numbers from the file dat to the textfields
        // we set every textfield to empty
        // line one empty
     
        // set the text fields 
        // when the user presses load, the saved numbers are inputted into the
        // jtextfields
    // they should be able to load up their saved numbers into the textfields
           try{
            File f = new File("output.dat");
            FileInputStream inStream = new FileInputStream(f);
            ObjectInputStream oStream = new ObjectInputStream(inStream);
            
            lotteryGuess = (ArrayList) oStream.readObject();
            lotteryGuessOne = (ArrayList) oStream.readObject();
            lotteryGuessTwo = (ArrayList) oStream.readObject();
            
            oStream.close();
            JOptionPane.showMessageDialog(null, "Reading");
            LineOneTextOne.setText(lotteryGuess.get(0).toString());
            LineOneTextTwo.setText(lotteryGuess.get(1).toString());
            LineOneTextThree.setText(lotteryGuess.get(2).toString());
            LineOneTextFour.setText(lotteryGuess.get(3).toString());
            LineOneTextFive.setText(lotteryGuess.get(4).toString());
        
            LineTwoTextOne.setText(lotteryGuessOne.get(0).toString());
            LineTwoTextTwo.setText(lotteryGuessOne.get(1).toString());
            LineTwoTextThree.setText(lotteryGuessOne.get(2).toString());
            LineTwoTextFour.setText(lotteryGuessOne.get(3).toString());
            LineTwoTextFive.setText(lotteryGuessOne.get(4).toString());
        
            LineThreeTextOne.setText(lotteryGuessTwo.get(0).toString());
            LineThreeTextTwo.setText(lotteryGuessTwo.get(1).toString());
            LineThreeTextThree.setText(lotteryGuessTwo.get(2).toString());
            LineThreeTextFour.setText(lotteryGuessTwo.get(3).toString());
            LineThreeTextFive.setText(lotteryGuessTwo.get(4).toString());
        
    
            } catch (FileNotFoundException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
   
    }//GEN-LAST:event_loadNumbersFromFileBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
        // when user presses delete do this 
        try{
            // create a new file!
            File f = new File("output.dat");
            if(f.exists()){
                // if the file exists already, delete it
                f.delete();
            }
            FileOutputStream os = new FileOutputStream(f);
            ObjectOutputStream outputStream = new ObjectOutputStream(os);
                os.close();
            
            }catch(IOException e){
                System.out.println(e.toString() + "Error!");
            }
        // when try catch exit do this 
        finally{
     
                dispose();
                lottoPhaseOneGUI lPhaseOne = new lottoPhaseOneGUI();
                lPhaseOne.setVisible(true);
                lPhaseOne.setLocationRelativeTo(null);
        }    
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lottoPhaseOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lottoPhaseOneGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField LineOneTextFive;
    private javax.swing.JFormattedTextField LineOneTextFour;
    private javax.swing.JFormattedTextField LineOneTextOne;
    private javax.swing.JFormattedTextField LineOneTextThree;
    private javax.swing.JFormattedTextField LineOneTextTwo;
    private javax.swing.JFormattedTextField LineThreeTextFive;
    private javax.swing.JFormattedTextField LineThreeTextFour;
    private javax.swing.JFormattedTextField LineThreeTextOne;
    private javax.swing.JFormattedTextField LineThreeTextThree;
    private javax.swing.JFormattedTextField LineThreeTextTwo;
    private javax.swing.JFormattedTextField LineTwoTextFive;
    private javax.swing.JFormattedTextField LineTwoTextFour;
    private javax.swing.JFormattedTextField LineTwoTextOne;
    private javax.swing.JFormattedTextField LineTwoTextThree;
    private javax.swing.JFormattedTextField LineTwoTextTwo;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel corrOneLbl;
    private javax.swing.JLabel corrThreeLbl;
    private javax.swing.JLabel corrTwoLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton drawBtn;
    private javax.swing.JTextField drawTextField;
    private javax.swing.JLabel enterTitleLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel fadeLbl;
    private javax.swing.JLabel genLottoLbl;
    private javax.swing.JLabel lineOneLbl;
    private javax.swing.JLabel lineOneResultLbl;
    private javax.swing.JTextField lineOneTF;
    private javax.swing.JLabel lineThreeLbl;
    private javax.swing.JLabel lineThreeResultLbl;
    private javax.swing.JTextField lineThreeTF;
    private javax.swing.JLabel lineTwoLbl;
    private javax.swing.JLabel lineTwoResultLbl;
    private javax.swing.JTextField lineTwoTF;
    private javax.swing.JButton loadNumbersFromFileBtn;
    private javax.swing.JTextField lottoMsgField;
    private javax.swing.JScrollPane lottoScrollPanelOne;
    private javax.swing.JTextArea lottoTextArea;
    private javax.swing.JButton pyBetBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveNumbersBtn;
    // End of variables declaration//GEN-END:variables
}
